### ISSUE TITLE
Discuss Link goes to Birthday Extension Post.

### ISSUE THREAD

**Issue by RelicSystem** [datlechin/flarum-copy-links#1]
Fairly straight forward, the discuss link in admin points to the birthdays extension. 
![Screenshot 2022-02-08 at 12 46 28](https://user-images.githubusercontent.com/700503/152920255-ecb1cb11-bd5c-45cd-91de-b3f0ec3e79da.png)

**Comment by datlechin** [comment]
Thanks @RelicSystem, it have fixed in v0.1.1
For now, the Discuss link not available
